[package]
name = "interceptor-vfs"
version = "0.0.1"
authors = ["Fernando Pereira <fernando.pereira@hadean.com>"]
description = "A libc interceptor virtual filesystem for Rust"
readme = "README.md"
keywords = ["vfs", "virtual", "filesystem"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
redhook = "2.0.0"

