[package]
name = "sandbox-vfs"
version = "0.0.1"
authors = ["Fernando Pereira <ferdonline@gmail.com>"]
description = "A libc-interposed virtual filesystem for Rust"
readme = "README.md"
keywords = ["vfs", "virtual", "filesystem"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
libc = "0.2.173"

[features]
hooks = []

[lib]
crate-type = ["dylib", "rlib"]
